title: Zani0x03
description: Blog de Tiago Zaniquelli AppSec Specialist Research Developer DotnetCore Python Ruby technology Information Security
google_analytics: G-L6WHJX1K50
theme: jekyll-theme-hacker